[package]
name = "day4"
version = "0.1.0"
edition = "2024"

[dependencies]
nom.workspace = true
glam.workspace = true 
divan.workspace = true

[[bench]]
name = "day4_bench"
path = "benches/benchmarks.rs"
harness = false