[package]
name = "day3"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools.workspace = true
divan.workspace = true

[[bench]]
name = "day3_bench"
path = "benches/benchmarks.rs"
harness = false