[package]
name = "day7"
version = "0.1.0"
edition = "2024"

[dependencies]
divan.workspace = true
nom.workspace = true
itertools.workspace = true
rustc-hash.workspace = true

[[bench]]
name = "day7_bench"
path = "benches/benchmarks.rs"
harness = false
