[package]
name = "day5"
version = "0.1.0"
edition = "2024"

[dependencies]
nom.workspace = true
divan.workspace = true
tracing.workspace = true
rangemap.workspace = true

[[bench]]
name = "day5_bench"
path = "benches/benchmarks.rs"
harness = false
