[package]
name = "day8"
version = "0.1.0"
edition = "2024"

[dependencies]
divan.workspace = true
glam.workspace = true
itertools.workspace = true
nom.workspace = true
tracing.workspace = true

[[bench]]
name = "day8_bench"
path = "benches/benchmarks.rs"
harness = false
